"""Declarative SQLAlchemy Base.

The Base carries the shared `MetaData` for every ORM model. We attach a
`naming_convention` here so Alembic generates deterministic names for
constraints and indexes — without it, autogenerated migrations get
random names and diff badly across machines.

The convention follows the SQLAlchemy docs and is the same one Alembic
recommends. Read it as: index → ix_<table>_<column>, unique → uq_...,
check → ck_..., foreign key → fk_..., primary key → pk_<table>.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Pinning these names lets `alembic revision --autogenerate` produce
# stable, reviewable migration diffs. Changing this dict later requires
# a migration to rename every existing constraint, so we set it once.
_naming_convention = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Common base for all ORM models.

    Models import this and subclass it. The metadata attached here is
    what Alembic's `target_metadata` points at in migrations/env.py.
    """

    metadata = MetaData(naming_convention=_naming_convention)
