"""create tasks table

Revision ID: 1ecce90525da
Revises:
Create Date: 2026-05-12 21:37:10.098865

This migration creates the only domain table for this brief along with
the `task_status` Postgres ENUM type that backs the status column.

The downgrade is hand-edited from Alembic's autogenerated default to
also drop the ENUM type. Without that, running `upgrade -> downgrade
-> upgrade` would fail with "type task_status already exists" because
DROP TABLE doesn't cascade to user-defined types.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ecce90525da"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


# Reused by both upgrade and downgrade so the type name lives in one
# place. `create_type=False` because op.create_table emits the CREATE
# TYPE on the column definition.
task_status_enum = sa.Enum(
    "todo",
    "in_progress",
    "done",
    name="task_status",
)


def upgrade() -> None:
    """Create the `tasks` table and the `task_status` ENUM type."""
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            task_status_enum,
            server_default="todo",
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )


def downgrade() -> None:
    """Drop the `tasks` table and the orphan `task_status` ENUM type."""
    op.drop_table("tasks")
    # Explicitly drop the ENUM type — Alembic's autogen leaves it behind.
    task_status_enum.drop(op.get_bind(), checkfirst=False)
